ref #12 Implemented the Show Post Feature using MVVM Architecture
HarikaKannuri-zs/User_RecyclerView_Application pull request #13
Opened 2024-07-16 07:48 UTC by HarikaKannuri-zs

To existing Add User and View User Application the Show Post Feature is added . The post are taken from API Calls with the implementation of retrofit and the  Show Post Feature is implemented by following the MVVM Architecture.

2024-07-18 08:02 UTC, MouzzamSiddiqui07 requested changes

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/MainActivity.kt
>      fun makeAPICall() {
Please make this fun private.

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/MainActivity.kt
> +                    Toast.makeText(this@MainActivity, "${result}.name", Toast.LENGTH_SHORT).show()
Please fix this code as it will not print the correct result name.

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/model/remote/userpostdata/UserPosts.kt
> +    val title : String,
Please try to create these member variables nullable as we don't know when we will get the data from api and when not.

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/view/addUser/AddUserFragment.kt
> +            addUserViewModel = ViewModelProvider(this@AddUserFragment).get(AddUserViewModel::class.java)
why are you creating the viewmodel instance on the click of the button?

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/view/addUser/AddUserFragment.kt
> +                addUserViewModel.insertUser(user)
Move this user validation logic in viewmodel.

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/view/showuserpost/ShowPostFragment.kt
> +        val recyclerView : RecyclerView = view.findViewById(R.id.postRecyclerView)
use apply block on recycler view to set the adapter and layout manager.

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/view/showuserpost/ShowPostFragment.kt
> +        postAdapter = PostAdapter()
Create the adapter with the help of lazy

2024-07-18 08:02 UTC, MouzzamSiddiqui07 commented on app/src/main/java/com/example/user_recyclerview/view/viewUser/ViewUserFragment.kt
> +import com.example.user_recyclerview.viewmodel.AddUserViewModel
Remove this unused import

2024-07-21 10:41 UTC, HarikaKannuri-zs commented
I have modified the code based on the above review and also created a
loadFragment function instead of using the same code two times. Please
review and notify me if any further changes are required.

On Thu, Jul 18, 2024 at 1:33 PM Mouzzam Siddiqui-ZS <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/src/main/java/com/example/user_recyclerview/MainActivity.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682289228>
> :
>
> >      override fun onCreate(savedInstanceState: Bundle?) {
>          super.onCreate(savedInstanceState)
>          setContentView(R.layout.activity_main)
>          makeAPICall()
>      }
> +    val api = RetrofitImplementation().retroObj()
>      fun makeAPICall() {
>
> Please make this fun private.
> ------------------------------
>
> In app/src/main/java/com/example/user_recyclerview/MainActivity.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682292400>
> :
>
> > @@ -30,11 +25,8 @@ class MainActivity : AppCompatActivity() {
>              ) {
>                  if (response.isSuccessful) {
>                      val result: List<UserResponse>? = response.body()
> -                    Toast.makeText(
> -                        ***@***.***,
> -                        "${result?.getOrNull(1)?.name}",
> -                        Toast.LENGTH_SHORT
> -                    ).show()
> +                    ***@***.***, "${result}.name", Toast.LENGTH_SHORT).show()
>
> Please fix this code as it will not print the correct result name.
> ------------------------------
>
> In
> app/src/main/java/com/example/user_recyclerview/model/remote/userpostdata/UserPosts.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682295963>
> :
>
> > @@ -0,0 +1,6 @@
> +package com.example.user_recyclerview.model.remote.userpostdata
> +
> +data class UserPosts(
> +    val title : String,
>
> Please try to create these member variables nullable as we don't know when
> we will get the data from api and when not.
> ------------------------------
>
> In
> app/src/main/java/com/example/user_recyclerview/view/addUser/AddUserFragment.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682350786>
> :
>
> > @@ -24,15 +25,13 @@ class AddUserFragment : Fragment() {
>          val userPhoneEditText: EditText = view.findViewById(R.id.userPhoneEditText)
>          val userAddButton: Button = view.findViewById(R.id.userAddButton)
>          userAddButton.setOnClickListener {
> +            addUserViewModel = ***@***.***).get(AddUserViewModel::class.java)
>
> why are you creating the viewmodel instance on the click of the button?
> ------------------------------
>
> In
> app/src/main/java/com/example/user_recyclerview/view/addUser/AddUserFragment.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682351368>
> :
>
> >              val userId = userIdEditText.text.toString()
>              val userName = userNameEditText.text.toString()
>              val userPhone = userPhoneEditText.text.toString()
>              if (userId.isNotBlank() && userName.isNotBlank() && userPhone.isNotBlank()) {
>                  val user = User(userId, userName, userPhone)
> -                val userDatabase =
> -                    UserDatabase.getDatabase((activity as MainActivity).applicationContext)
> -                val userDao = userDatabase.userDao()
> -                userDao.insertUser(user)
> +                addUserViewModel.insertUser(user)
>
> Move this user validation logic in viewmodel.
> ------------------------------
>
> In
> app/src/main/java/com/example/user_recyclerview/view/showuserpost/ShowPostFragment.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682358982>
> :
>
> > +import com.example.user_recyclerview.R
> +import com.example.user_recyclerview.viewmodel.ShowPostViewModel
> +
> +class ShowPostFragment : Fragment() {
> +    private lateinit var postAdapter: PostAdapter
> +    private lateinit var showPostViewModel : ShowPostViewModel
> +    override fun onCreateView(
> +        inflater: LayoutInflater, container: ViewGroup?,
> +        savedInstanceState: Bundle?
> +    ): View? {
> +        return inflater.inflate(R.layout.fragment_show_post, container, false)
> +    }
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
> +        super.onViewCreated(view, savedInstanceState)
> +        showPostViewModel = ***@***.***).get(ShowPostViewModel::class.java)
> +        val recyclerView : RecyclerView = view.findViewById(R.id.postRecyclerView)
>
> use apply block on recycler view to set the adapter and layout manager.
> ------------------------------
>
> In
> app/src/main/java/com/example/user_recyclerview/view/showuserpost/ShowPostFragment.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682359372>
> :
>
> > +
> +class ShowPostFragment : Fragment() {
> +    private lateinit var postAdapter: PostAdapter
> +    private lateinit var showPostViewModel : ShowPostViewModel
> +    override fun onCreateView(
> +        inflater: LayoutInflater, container: ViewGroup?,
> +        savedInstanceState: Bundle?
> +    ): View? {
> +        return inflater.inflate(R.layout.fragment_show_post, container, false)
> +    }
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
> +        super.onViewCreated(view, savedInstanceState)
> +        showPostViewModel = ***@***.***).get(ShowPostViewModel::class.java)
> +        val recyclerView : RecyclerView = view.findViewById(R.id.postRecyclerView)
> +        recyclerView.layoutManager = LinearLayoutManager(context)
> +        postAdapter = PostAdapter()
>
> Create the adapter with the help of lazy
> ------------------------------
>
> In
> app/src/main/java/com/example/user_recyclerview/view/viewUser/ViewUserFragment.kt
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#discussion_r1682388842>
> :
>
> >  import com.example.user_recyclerview.view.viewUser.adapter.UserAdapter
> +import com.example.user_recyclerview.viewmodel.AddUserViewModel
>
> Remove this unused import
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HarikaKannuri-zs/User_RecyclerView_Application/pull/13#pullrequestreview-2184865875>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJSCWG2ZAKR2TFCFVH5SY5TZM5ZETAVCNFSM6AAAAABK6AGMVOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOBUHA3DKOBXGU>
> .
> You are receiving this because you authored the thread.Message ID:
> <HarikaKannuri-zs/User_RecyclerView_Application/pull/13/review/2184865875@
> github.com>
>

2024-07-23 07:23 UTC, merged